server:
  port: 8080
  error:
    whitelabel:
      enabled: true

spring:
  main:
    banner-mode: off
  profiles:
    active: local
  data:
    web:
      pageable:
        one-indexed-parameters: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

# local
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3307/shop?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mariadb://localhost:3306/develop?useUnicode=true&characterEncoding=utf-8
#      username: develop
#      password: develop
#      driver-class-name: org.mariadb.jdbc.Driver
    sql-script-encoding: utf-8
#         data: classpath:sql-data/corporations.sql,classpath:sql-data/merchants.sql,classpath:sql-data/card_bins.sql,classpath:sql-data/pay_methods.sql,classpath:sql-data/payment_transaction_types.sql,classpath:sql-data/develop.sql,classpath:sql-data/member_payment_methods.sql,classpath:sql-data/service_access_history.sql,classpath:sql-data/test.sql,classpath:sql-data/admin_menu.sql
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.show_sql: true
      hibernate.format_sql: true
#  redis:
#    payment:
#      host: 127.0.0.1
#      port: 6379
#      password: develop
#      database: 0
  devtools:
    restart:
      enabled: false
  jackson:
    serialization:
      fail-on-empty-beans: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
#server:
#  port: 8083

# dev
---
spring:
  profiles: dev
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://cpay-dev-cpay-data-mariadb-ms:3306/my_database?useUnicode=true&characterEncoding=utf-8
      username: koot
      password: eYo5z8V0kA
      driver-class-name: org.mariadb.jdbc.Driver
    sql-script-encoding: utf-8
    initialization-mode: never
    # data: classpath:sql-data/develop.sql,classpath:sql-data/corporations.sql,classpath:sql-data/card_bins.sql,classpath:sql-data/pay_methods.sql,classpath:sql-data/payment_transaction_types.sql,classpath:sql-data/admin_menu.sql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.show_sql: true
      hibernate.format_sql: true
  devtools:
    restart:
      enabled: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
# qa
---
spring:
  profiles: qa

# prod
---
spring:
  profiles: prod