server:
  port: 8080
  error:
    whitelabel:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/shop?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver